# Generated by Django 5.2.4 on 2025-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
    ]
