# Generated by Django 5.2.4 on 2025-07-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
