# Generated by Django 5.2.4 on 2025-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0002_concert_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("address", models.CharField(max_length=255)),
                ("detail_location", models.TextField()),
            ],
        ),
    ]
