# Generated by Django 5.2.4 on 2025-07-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0003_locker"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="ticket_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
