# Generated by Django 5.2.4 on 2025-07-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0004_concert_ticket_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("ticket_url", models.URLField(blank=True, null=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Musical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("ticket_url", models.URLField(blank=True, null=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
    ]
